### PR TITLE
usb-midi i/o example

### PR DESCRIPTION
**Pull request by x37v**

### CODE REVIEW

**Comment by mtthw-meyer** [comment]
Looks good. I'll see what is up with the CI.

**Comment by x37v** [comment]
there is an error `panicking in constants is unstable` .. I'm not sure where that is coming from but I assume that is happening to me in another branch where i'm trying to upgrade the HAL..

**Comment by x37v** [comment]
looks like they added const panic in rust `1.57`
okay to upgrade the CI and set the minimum supported rust version?
https://github.com/rust-lang/rust/blob/master/RELEASES.md#version-1570-2021-12-02

**Comment by mtthw-meyer** [comment]
> looks like they added const panic in rust `1.57` okay to upgrade the CI and set the minimum supported rust version? https://github.com/rust-lang/rust/blob/master/RELEASES.md#version-1570-2021-12-02

Might as well bump it up to 1.60.

**Review by mtthw-meyer — APPROVED** [review]

**Pull request merged**
