### PR TITLE
Basic SDRAM functionality

### PR DESCRIPTION
**Pull request by glindstedt**
I took a stab at getting the SDRAM chip running using the stm32h7-fmc crate (branch for adding the memory chip here https://github.com/glindstedt/stm32h7-fmc/commit/bf85a185a0e34b5306248d95088656a374c87a78, the timings could probably be tuned more)

It seems to be working, but I haven't done any advanced testing, only what's done in the example. I had to break up the `GPIO::init` fuction arguments so it wouldn't take ownership of all the pins, as some were to be used for the FMC. The MPU initialization was copied from the stm32h7-fmc crate and might not match 1-1 what libDaisy is doing at the moment.

I've also noticed that there's a more general fmc crate now: https://github.com/stm32-rs/stm32-fmc
Maybe this is what should be used instead, and seems to have more recent development, but not sure what the status is.

Not sure what ideas you've had for how the user would interface with the SDRAM, by passing around a mut slice or perhaps using an allocator?

I don't think this is ready to be merged to master, given that it depends on an unmerged branch, but I figured I'd show what I've got so far.

### CODE REVIEW

**Comment by mtthw-meyer** [comment]
I'd expect the nominal use case to be static arrays in the SDRAM.

**Comment by glindstedt** [comment]
Looks like there's a PR for integrating the stm32-fmc crate into stm32h7xx-hal https://github.com/stm32-rs/stm32h7xx-hal/pull/116

I'll probably pause this PR until that's been merged so I can migrate

**Comment by mtthw-meyer** [comment]
Sounds good.

**Comment by mtthw-meyer** [comment]
That PR has merged and the I2S one will be merged soon. Once stm32h7xx-hal v0.8.0 is released should be able to resume work on some of this stuff.

**Comment by glindstedt** [comment]
Yeah I was waiting on the I2S stuff also since there were issues with transitive dependencies that didn't use the sai-i2s branch. I'll pick up work again once 0.8 is out and I have time for it.

**Comment by mtthw-meyer** [comment]
I've landed updates to bring the crates up to using 0.9.0 HAL now. Getting SDRAM working along with the right memory.x should be doable now.

**Comment by mtthw-meyer** [comment]
Superseded by #10

**Pull request closed without merging**
