### PR TITLE
Xnor/rtic upgrade

### PR DESCRIPTION
**Pull request by x37v**
* upgraded to rtic 1.0
* removed `_bss` from sdram.. quick search made me think it isn't zeroed, which is what `_bss` indicates

### CODE REVIEW

**Comment by x37v** [comment]
looks like `rtic-core` uses `2021` which requires rust `1.56.0` or later.
That is 2 minor versions behind the current `1.58.0` .. any reason not to put min to `1.56` ?

**Comment by mtthw-meyer** [comment]
Moving up the latest is fine. You'll also need to update the CI to use that version.

**Comment by x37v** [comment]
> Moving up the latest is fine. You'll also need to update the CI to use that version.

done

**Review by mtthw-meyer — APPROVED** [review]
LGTM

**Pull request merged**
